
# Stage 1: Build Frontend
FROM node:20-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Runtime
FROM node:20-alpine AS production-stage
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY --from=build-stage /app/dist ./dist
COPY server.js ./
COPY types.ts ./

# Fix permissions to prevent 403 Forbidden
RUN chmod -R 755 /app/dist

EXPOSE 8080
# Limit memory for Node on t3.micro
CMD ["node", "--max-old-space-size=450", "server.js"]
